### ISSUE TITLE
Having an issue when I double click on a game on the list

### ISSUE THREAD

**Issue by Saigaiii** [hotshotz79/PS5-Activity-Log#1]
Here are the details of the unhandled exception that pops up: https://pastebin.com/75cTLzpq

**Comment by hotshotz79** [comment]
Please confirm if you waited until after the activity log database is downloaded and _then_ double clicked

If you did wait and then double clicked on a game, can you tell me if its for all the games or just one?

**Comment by Saigaiii** [comment]
> Please confirm if you waited until after the activity log database is downloaded and _then_ double clicked
> 
> If you did wait and then double clicked on a game, can you tell me if its for all the games or just one?

My fault for not responding sooner. Everything is working fine now after a restart of my PC. BTW awesome program bro!

**Comment by hotshotz79** [comment]
Awesome and thank you
